openapi: 3.0.0
info:
  title: Announcements v3
  version: '3.0'
  description: ''
  contact:
    name: Tom Zagorski
    url: signalkit.com
servers:
  - url: 'https://app.signalkit.com/api/announcements/v3'
paths:
  '/announcements/{id}/':
    get:
      summary: Get the announcements visible to the user
      tags: []
      responses: {}
      description: ''
      security:
        - OAuth2: []
    parameters:
      - schema:
          type: number
        name: id
        in: path
    post:
      summary: Create one/many announcements
      responses:
        '200':
          description: OK
    put:
      summary: Update an announcement
      responses:
        '200':
          description: OK
    delete:
      summary: Delete an announcement
      responses:
        '200':
          description: OK
components:
  securitySchemes:
    OAuth2:
      type: oauth2
